// <auto-generated/>
// Generated by Forge from an attribute set definition. Edits here are lost the next time the definition
// is saved. To add logic to this set, override AttributeOnValueChanged, PreEffectExecute or
// PostEffectExecute in a separate file declaring the same partial class.

using Gamesmiths.Forge.Attributes;

namespace Gamesmiths.Forge.Godot.Generated;

public partial class @MovementAttributes : AttributeSet
{
	public EntityAttribute @Speed { get; private set; }

	public @MovementAttributes()
	{
		@Speed = InitializeAttribute(nameof(@Speed), 500, 0, 2000, 1, 2);
	}
}
