name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./artifacts/*
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
